require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Layout/LineLength:
  Max: 120

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/MissingExampleGroupArgument:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - spec/**/*

RSpec/NamedSubject:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false
